### ISSUE TITLE
BUG - Capitalization and spelling of items in "Datasources > Post Categories"

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#150]
Site: Quansight LLC

----

Problem 1: Inconsistent `Datasources > Post Category` capitalization

- Item "PyData ecosystem"  should be  "PyData Ecosystem" (capital 'E')
- Item "Scalable computing" should be "Scalable Computing" (capital 'C')

I believe this requires admin rights to fix?

----

Problem 2: Misspelled kebab-case tag in `Datasources > Post Category`

- Tag "Infrastructure-hcp" should be "infrastructure-hpc"  ('hcp' becomes 'hpc')

This looks like I could change it myself, but based on the onboarding I didn't want to attempt it without guidance.

----

Annotated screenshot:

![image](https://user-images.githubusercontent.com/11325439/171685232-bd366996-45d3-4a7e-977d-6f3d44d2bd45.png)

**Comment by galdranorn** [comment]
@bskinn changed as described. datasource changing needs an admin role in Storyblok, it seems that you probably have an editor one.
