### ISSUE TITLE
[QA] - Quansight LLC (staging)

### ISSUE THREAD

**Issue by trallard** [Quansight/Quansight-website#152]
## URLs

- [Preview (staging) for LLC](https://github.com/Quansight/Quansight-website/deployments/activity_log?environment=Preview+%E2%80%93+quansight-consulting)
- [Production for LLC](https://github.com/Quansight/Quansight-website/deployments/activity_log?environment=Production+%E2%80%93+quansight-consulting)

### Functional

- [ ] Check [against initial specification doc](https://docs.google.com/document/d/196XZSMPNzT6-J3DtbI_uHG66-cBk9grh5e0u6_LDt1k/edit)
- [ ] Forms and integrations 
	- [ ] Greenhouse (displaying current jobs) -- @bskinn 
	- [ ] Pipedrive (can use the form and the validation is working - no required fields can be left empty, email validation) -- @bskinn 
	- [ ] Mailchimp (submit form cannot be empty, email validation) -- @bskinn 
- [ ] Check hyperlinks (wonder if we should look into adding tests for this - through CI - though this might change the workflow with Vercel 🤔 )
	- [ ] Internal hyperlinks
	- [ ] External
- [ ] Check [loading speed](https://pagespeed.web.dev/)
- [ ] Components work as expected (not adding a comprehensive list here - carousels, links, buttons, dropdowns, etc.)

### Browsers

- [ ] Browser compatibility
	- [ ] Mobile
	- [ ] Chromium based web browsers
	- [ ] Safari
	- [ ] Firefox
	- [ ] Edge (?)

### CMS 

- [ ] Preview is working as expected
- [ ] Staging is content is updated once `Publish` in Storyblok is used
- [ ] Metadata for images, content types and others is adequately pre-defined (i.e. fields needed)

### Repository

- [ ] Technical documentation is included
	- [ ] Deployment and maintenance related
	- [ ] Dependencies and libraries are listed
	- [ ] How the repo is structured (where things live)
	- [ ] Coding standards are documented

	
### SEO

**Comment by gabalafou** [comment]
@bskinn could I delegate to you the QA tasks under checking forms and integrations? I really need to focus my efforts on accessibility, URL routing, and some of the other QA tasks.

**Comment by bskinn** [comment]
@gabalafou Sure, I can take those two.

- Greenhouse -- Can I just check this against the jobs listing on the current site?
- Pipedrive -- I'll also work with @bsodenkamp to make sure that the submitted data reaches the correct Pipedrive pipelines

Raises the question, @bsodenkamp: Will it be a problem to test the new site using the "live" Pipedrive pipelines? (E.g., we can let Sales know that some test data will be passing through, and they'll ignore?) Or, will we need to set up some temporary pipelines for testing?

**Comment by bsodenkamp** [comment]
@bskinn the sales team does not see inputs from the website until I pass them along, so this should not be an issue.

**Comment by bskinn** [comment]
@gabalafou Re the forms/integrations on LLC:

- Integration function
  - The Greenhouse integration is working -- job listings are populating
  - The Zapier integrations with Pipedrive are confirmed working
  - The Zapier integration with Mailchimp is working
- Form validation
  - News & updates email signup form on `/library`
    - OK: Rejects empty input
    - WEAK EMAIL VALIDATION: Only checks for presence of `@` in input
  - Contact forms on `/about-us` and services pages
    - OK: Rejects empty input for all fields
    - WEAK EMAIL VALIDATION: Only checks for presence of `@`
    - NO PHONE VALIDATION: Accepts even non-numeric inputs

**Comment by gabalafou** [comment]
As discussed with @trallard, there's no need to have two separate issues for production versus staging for QA. They can be done on staging or production, the result should be the same. So I'm closing all of the versions of this issue marked for staging.
