### ISSUE TITLE
[QA] - Labs site (staging)

### ISSUE THREAD

**Issue by trallard** [Quansight/Quansight-website#153]
Please start with #152 

## URLs

- [Preview (staging) for LLC](https://github.com/Quansight/Quansight-website/deployments/activity_log?environment=Preview+%E2%80%93+quansight-labs)
- [Production for LLC](https://github.com/Quansight/Quansight-website/deployments/activity_log?environment=Production+%E2%80%93+quansight-consulting](https://github.com/Quansight/Quansight-website/deployments/activity_log?environment=Production+%E2%80%93+quansight-labs))

### Functional

- [ ] Check [against initial specification doc](https://docs.google.com/document/d/196XZSMPNzT6-J3DtbI_uHG66-cBk9grh5e0u6_LDt1k/edit)
- [ ] Forms and integrations 
	- [ ] Greenhouse (displaying current jobs)
	- [ ] Pipedrive (can use the form and the validation is working - no required fields can be left empty, email validation)
- [ ] Check hyperlinks (wonder if we should look into adding tests for this - through CI - though this might change the workflow with Vercel 🤔 )
	- [ ] Internal hyperlinks
	- [ ] External
- [ ] Check [loading speed](https://pagespeed.web.dev/)
- [ ] Components work as expected (not adding a comprehensive list here - carousels, links, buttons, dropdowns, etc.)

### Browsers

- [ ] Browser compatibility
	- [ ] Mobile
	- [ ] Chromium based web browsers
	- [ ] Safari
	- [ ] Firefox
	- [ ] Edge (?)

### CMS 

- [ ] Preview is working as expected
- [ ] Staging is content is updated once `Publish` in Storyblok is used
- [ ] Metadata for images, content types and others is adequately pre-defined (i.e. fields needed)

### Repository

- [ ] Technical documentation is included
	- [ ] Deployment and maintenance related
	- [ ] Dependencies and libraries are listed
	- [ ] How the repo is structured (where things live)
	- [ ] Coding standards are documented

	
### SEO

**Comment by trallard** [comment]
@gabalafou can you please prioritise this and the accessibility checks for Labs? 
These need to be completed soon and I anticipate will uncover bugs or the such which will need to be added to the queue. Right now all the issues come from the Storyblok use cases and workflows.

**Comment by gabalafou** [comment]
This is indeed my highest priority now that I've helped sort through the GitHub issues. 

I've been working assiduously on the sections of this task "CMS" and "Repository":

- CMS: https://github.com/Quansight/Quansight-website/pull/167
- Repository: #234, #166, #235

But the sections "Functional" and "Browsers" need more attention.

**Comment by gabalafou** [comment]
As discussed with @trallard, there's no need to have two separate issues for production versus staging for QA. They can be done on staging or production, the result should be the same. So I'm closing all of the versions of this issue marked for staging.
