### ISSUE TITLE
[QA] - Quansight LLC (production)

### ISSUE THREAD

**Issue by trallard** [Quansight/Quansight-website#159]
## URLs

- [Preview (staging) for LLC](https://github.com/Quansight/Quansight-website/deployments/activity_log?environment=Preview+%E2%80%93+quansight-consulting)
- [Production for LLC](https://github.com/Quansight/Quansight-website/deployments/activity_log?environment=Production+%E2%80%93+quansight-consulting)

### Functional

- [ ] Check [against initial specification doc](https://docs.google.com/document/d/196XZSMPNzT6-J3DtbI_uHG66-cBk9grh5e0u6_LDt1k/edit)
- [ ] Forms and integrations 
	- [ ] Greenhouse (displaying current jobs)
	- [ ] Pipedrive (can use the form and the validation is working - no required fields can be left empty, email validation)
	- [ ] Mailchimp (submit form cannot be empty, email validation)
- [ ] Check hyperlinks (wonder if we should look into adding tests for this - through CI - though this might change the workflow with Vercel 🤔 )
	- [ ] Internal hyperlinks
	- [ ] External
- [ ] Check [loading speed](https://pagespeed.web.dev/)
- [ ] Components work as expected (not adding a comprehensive list here - carousels, links, buttons, dropdowns, etc.)

### Browsers

- [ ] Browser compatibility
	- [ ] Mobile
	- [ ] Chromium based web browsers
	- [ ] Safari
	- [ ] Firefox
	- [ ] Edge (?)

### CMS 

- [ ] Preview is working as expected
- [ ] Staging is content is updated once `Publish` in Storyblok is used
- [ ] Metadata for images, content types and others is adequately pre-defined (i.e. fields needed)

### Repository

- [ ] Technical documentation is included
	- [ ] Deployment and maintenance related
	- [ ] Dependencies and libraries are listed
	- [ ] How the repo is structured (where things live)
	- [ ] Coding standards are documented

	
### SEO

**Comment by gabalafou** [comment]
I have a few questions.

> Metadata for images, content types and others is adequately pre-defined (i.e. fields needed)

I need you to elaborate on this one a bit more. I have an idea of what you're asking me to check, but I'm not sure.

>  Coding standards are documented

I'm not sure this is needed. Developers should be able to follow the general pattern and there are also git hooks that enforce coding standards. 

>  Dependencies and libraries are listed

I think this is just package.json. For this and for the coding standards, would it be sufficient to add a note to the readme? Something like this:

```
## Coding standards

Coding standards are enforced by git hooks. See .git/hooks/... blah blah 

You can also use existing code to infer conventions (double vs single quotes, etc.).

## Dependencies and libraries

The website is a typical NPM package; its dependencies are defined in package.json.

You can actually make changes to code from within GitHub and Vercel will deploy the changes to a special preview site just for those changes. When you open a PR, the system will add a comment to the PR with details.

If you wish to develop locally, you will need to meet the system requirements and install the dependencies with `npm install`.
```

Actually that raises a question for me. I honestly don't know how to use `npm` with package-lock.json. I stopped using npm a long time ago in favor of yarn. I'll add that as something to ask Naturaily. In other words, we should add a note about the package-lock.json file to the repo's README.

**Comment by gabalafou** [comment]
Created issue (https://github.com/Quansight/Quansight-website/issues/168) to track question about package-lock.json

**Comment by gabalafou** [comment]
Also see discussion at https://github.com/Quansight/Quansight-website/issues/152.
