### ISSUE TITLE
[BUG] - Duplicate link to blog post on LLC/Library page

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#171]
### What site is this for?

Quansight LLC

### Expected behavior

There should be a strict one-to-one mapping between the entries under [library/blog in Storyblok](https://app.storyblok.com/#!/me/spaces/147759/stories/0/0/index/143967725?page=1) and what appears on the [library page with the type=blog filter](https://quansight-consulting.vercel.app/library?page=1&type=blog) applied.

### Actual behavior

Some blog entries are duplicated. I suspect this is a bug in the front-end code because I notice that duplication happens on either side of newsletter signup break, so as a programmer, I suspect that there's some kind of indexing/counting error.

### How to Reproduce the problem?

1. Visit [LLC Blog List](https://quansight-consulting.vercel.app/library?page=1&type=blog)
2. Observe that there are duplicated entries in the list.
3. Verify that there are not, however, duplicated entries in Storyblok admin. Go to LLC > Content > Library > Blog.

### Anything else?

Here are two screenshots showing the duplication described above. In the first screenshot the link to the "Dask" blog post is duplicated on either side of the newsletter signup. In the second screenshot, the link to the "RAPIDS" blog post is duplicated on either side of the signup.

"Dask" is duplicated:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/317883/173025652-afb3e963-3569-443f-a60d-048596794a4c.png">

"RAPIDS cuCIM" is duplicated:

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/317883/173030119-98272816-67f1-4f97-b6f7-a8c15b86669f.png">

**Comment by gabalafou** [comment]
cc @kherma

**Comment by kherma** [comment]
Hi, if everything is fine, can we close this issue?

**Comment by gabalafou** [comment]
Closing for now. Can reopen if there are still issues.

**Comment by bskinn** [comment]
To mark: This issue is still occurring on Storyblok as of just now (16:07 UTC on 2022-06-21), likely because the fix of #173 has not yet reached `main`.
