### ISSUE TITLE
[BUG] - Blog posts have been “unpublished” in Storyblok, but they still appear in the blog post listing on the Library page

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#172]
### What site is this for?

Quansight LLC

### Expected behavior

Here's what I expect, but this may not match the expectations of the team as a whole. We are still working out what the team consensus is. See https://github.com/Quansight/Quansight-website/pull/167.

Hit save button on consulting blog post:

- Should appear in Storyblok preview mode (i.e., when `preview` is appended in query string params)
- Should not appear on staging
- Should not appear on production

Hit publish button on consulting blog post:

- Should continue to appear in preview mode
- After a build delay, should appear on staging
- Should not appear on production

Click unpublish on (published) blog post:

- Should continue to appear in preview mode (because it's still saved)
- After a build delay, it should disappear from staging
- Should not appear on production

By staging I mean the build that is triggered by the publish/unpublish hook currently configured in Storyblok: 
https://api.vercel.com/v1/integrations/deploy/VERCEL_KEY/BRANCH_KEY

In Vercel, the above URL is mapped to the develop branch. That makes me think that the following URL should be the de facto staging URL:
https://quansight-consulting-git-develop-quansight.vercel.app/

Currently, production in Vercel is mapped to:
https://quansight-consulting.vercel.app/

### Actual behavior

At the time of writing this issue, there were 17 total LLC blog posts in Storyblok. 3 of them were published, 14 unpublished.

Here's a table summarizing what I discovered at the following URLs:

| Description | URL | Number blog post links |
| ----------- | ----- | ---------------------- |
| Staging/develop? | https://quansight-consulting-git-develop-quansight.vercel.app/library?page=1&type=blog | 17 |
| Production | https://quansight-consulting.vercel.app/library?page=1&type=blog | 10 |
| Storyblok preview | https://quansight-consulting.vercel.app/api/preview?secret=SECRET&slug=library/ | 17 |

### How to Reproduce the problem?

Publish / unpublish a blog post and see whether it appears / disappears at any URL, whether production, staging, or preview.

**Comment by bskinn** [comment]
I would add some extra specificity to the visibility at the production site: what is seen on production is the state of staging at the time of the last Vercel build/deploy to prod.

@gabalafou, perhaps for each of your sets of bullets in 'Expected behavior', you meant there also to be a Vercel build/deploy to prod?

**Comment by gabalafou** [comment]
I think I know why this is happening. When Naturaily handed over the site to us, there were only preview tokens in Vercel and references to those preview tokens in the code. 

We need to add public Storyblok tokens to Vercel and change the code to be able to use preview vs public tokens where appropriate.

I can't do this myself because I don't totally understand how the codebase uses the tokens currently defined in Vercel. For example, I don't understand the difference between `NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN` and `STORYBLOK_PREVIEW_TOKEN`. You can find references to both of those in the codebase.

*NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN is a very confusing name for that token since it mixes "public" and "preview" in the same string, and in Storyblok lingo, those two are not simultaneously compatible.

**Comment by marcin-antczak-naturaily** [comment]
This is caused by wrong configuration on vercel. We agreed to split into 2 domains. Production domain is going to use STORYBLOK_TOKEN while staging is going to use STORYBLOK_PREVIEW_TOKEN. In this way unpublished content won't be visible on production.
