### ISSUE TITLE
[BUG] Columns component - alignment of tops of text/paragraph across all columns

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#175]
This screenshot shows how the paragraph text (not the icon, not the title, the paragraph text) in the columns is not aligned:

![](https://user-images.githubusercontent.com/11325439/173701588-209d3f81-e6db-4192-8c17-7de55ace2352.png)

Irina would like the paragraph text to all be top-aligned.

This issue probably went unnoticed until the actual column titles were added, because previously the filler titles would all fit on one line. And when each column title is one line, then all of the text paragraphs align naturally.

### How to reproduce:

You can see the issue at the following URL: 
https://quansight-consulting-git-develop-quansight.vercel.app/data-engineering-mlops

**Comment by kherma** [comment]
Hi, just to clarify, So if we have a row of columns, and some columns have 2-lines heading and some 1-line heading, you want the paragraphs below the headings to start on the same level, so no matter how many lines the heading has, the red line from example image will always be straight. Is that correct?

**Comment by bskinn** [comment]
@kherma, that's right, the red line should always be horizontal, regardless of different numbers of lines of heading text in the various headings
