### ISSUE TITLE
[INFO] - Specifications for Hero images (size? different versions for mobile/desktop?)

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#177]
### What site is this for?

Quansight LLC

### Actual behavior

Naturaily, please provide any guidance you have about optimal sizes for Hero images. 

Also, do we need to upload different Hero image versions for desktop vs mobile? If so, how do we indicate these multiple images on the Storyblok Hero component?

Thanks!

**Comment by bskinn** [comment]
This is downstream of #213

**Comment by gabalafou** [comment]
To me, this feels like something missing from [the Storyblok manual](https://docs.google.com/document/d/1HVaWKhepSxIQP1ZY9o7O_n3qCQpE8KdgD9KIaS4P-n4/edit#heading=h.enx0tixw76df).

**Comment by gabalafou** [comment]
at-team-Naturaily: my guess is that we need to upload images at a large width (like 3000 px?) and then the image resizer service will size the image down to smaller widths for screens with lower resolutions. 

Whatever the case, we would love for the exact details to be in the manual.
