### ISSUE TITLE
[MISSING FEAT] Ability to embed Youtube video in a blog post

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#178]
This is for Consulting LLC site.

On the current Quansight blog, here is [an example of a blog post with an embedded Youtube video](https://www.quansight.com/post/why-we-are-excited-about-jupyterlab-3-0-dynamic-extensions).

We're not sure how to do this with the new website.

Note: this feature seems like it was in [the requirements doc](https://docs.google.com/document/d/196XZSMPNzT6-J3DtbI_uHG66-cBk9grh5e0u6_LDt1k/edit#heading=h.3szh42w5yu7r).

**Comment by trallard** [comment]
This was but not specified that this was under blog posts. But all the conversations around this centred on the "Library" 

If we absolutely need to add videos is it not enough to embed the YouTube iframe? Might be worth checking

**Comment by bskinn** [comment]
I don't think we have the technical capability to add a YouTube iframe to a post in Storyblok atm.

**Comment by trallard** [comment]
Adding some links for research

- https://www.storyblok.com/faq/how-can-i-embed-a-codepen-in-a-site-i-made-with-storyblok
- https://www.storyblok.com/tp/how-to-add-vimeo-video-headless-cms
- https://bejamas.io/blog/jamstack-video/ (see YouTube embeds)
