### ISSUE TITLE
[MISSING FEAT] Blog post attachments (download links)

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#179]
This is for the Consulting LLC site.

Context: [some blog posts have attachments](https://www.quansight.com/post/quick-dashboarding-with-panel).

We would like a way to add download links to blog posts.

This seems like it was in [the requirements doc](https://docs.google.com/document/d/196XZSMPNzT6-J3DtbI_uHG66-cBk9grh5e0u6_LDt1k/edit#heading=h.7xc8e179xaqc).

**Comment by trallard** [comment]
Similar to the YouTube issue - this was mostly discussed from the library perspective and not blogs. 

How necessary is this? Can the respective pdf be added to the library and x-link from the post? Ultimately a download link is a URL with the download directive or so

**Comment by bskinn** [comment]
After testing:

- It is **not** possible to use the image insertion machinery to display other file types.
- It **IS** possible to add arbitrary files to the Assets in Storyblok and then link to those assets
  1. Add and file the desired asset using the Assets pane of the Storyblok interface (left-hand nav menu)
  2. Once uploaded, click on the new asset in the Assets pane to pop up the detailed information view
  3. Go to the blog post where the link is to be added
  4. Type the text of the link
  5. Highlight the link text and click the chain icon to add a link
  6. Use the Asset Manager to locate and select the desired file
  7. Select "New window" from the Target drop-down
  8. Click 'Ok' to apply the link to the text

This method does not provide as attractive a presentation as the Wix machinery did for the old blog, but it should be functional enough.
