### ISSUE TITLE
[FEAT] Controlling image size in blog posts

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#181]
This applies to the Consulting site.

Examples of where/why this is needed:

- The workflow diagram images for the [Up and Running with Prefect post](https://quansight-consulting-git-develop-quansight.vercel.app/library/blog/up-and-running-with-prefect)
- Shrinking the project names/logos used as section headers in the [OSS NLP Getting Started post](https://quansight-consulting-git-develop-quansight.vercel.app/library/blog/open-source-natural-language-processing-libraries-to-get-you-started)
- More examples at the [Panel/Holoviews Learning Aid post](https://quansight-consulting-git-develop-quansight.vercel.app/library/blog/panel-holoviews-learning-aid), especially e.g. the “My Radio Button App” image

**Comment by gabalafou** [comment]
This isn't covered by [the requirements doc](https://docs.google.com/document/d/196XZSMPNzT6-J3DtbI_uHG66-cBk9grh5e0u6_LDt1k/edit) as far as I can tell, so this is on us. However, I think having Naturaily's expertise on this task could save us lots of time.

**Comment by tokordys** [comment]
@marcin-antczak-naturaily Your input here would be needed to define what approach would be best.

**Comment by bskinn** [comment]
This is `owner: Quansight` -- but, @marcin-antczak-naturaily, any input will be welcomed here, to guide our efforts to implement the feature.

**Comment by bskinn** [comment]
@kherma Please **halt work** on this issue until after launch. There are other issues emerging of higher priority.

**Comment by bskinn** [comment]
With the Consulting blog machinery migration of #396 / #577, image size in blog posts for both sites can be controlled using explicit `<img />` tags and the usual `height`/`width` attributes:

```html
<img
  src="..."
  alt="..."
  width="600px"
/>
```

Due to MDX/JSX syntactic requirements, a self-terminating HTML tag (`<img />`) **MUST** be used.
