### ISSUE TITLE
[BUG] - Storyblok changes URLs to blog posts

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#183]
### What site is this for?

Quansight LLC

### Expected behavior

Blog posts on Wix had `/post/` in the URL slug; Storyblok does not have `/post/` in the URL slug

### Actual behavior

URL paths stay the same.

### How to Reproduce the problem?

Url path of blog post at new site:
[/library/blog/rapids-cucim-porting-scikit-image-code-to-the-gpu](https://quansight-consulting.vercel.app/library/blog/rapids-cucim-porting-scikit-image-code-to-the-gpu)

Same blog post via old site:
[/post/performance-for-image-processing-with-cucim](https://www.quansight.com/post/performance-for-image-processing-with-cucim)

### Anything else?

Note from Brian:

Might be a constraint of Storyblok, or there may be an admin setting we can adjust, that will make the blog posts have slugs of "/post/abc-xyz" instead of "/library/blog/abc-xyz".

Otherwise, we will probably want to set up redirects (with Vercel?) from the old "/post/abc-xyz" routes to the new.

Actually, it would probably be a good idea to also route any other requests to "/post/abc-xyz" (for posts that we did not migrate) to e.g. "/library"

**Comment by trallard** [comment]
Is this also a pattern in Labs @noatamir ?

**Comment by noatamir** [comment]
Not exactly.
Here's the url path for the last post on the old site: 
[/blog/2022/05/the-evolution-of-the-scipy-developer-cli/ ](https://labs.quansight.org/blog/2022/05/the-evolution-of-the-scipy-developer-cli/)

The root is `blog`, without the word `library`. And we have the `year/month`sub-structure, which I assume is not a problem?

**Comment by bskinn** [comment]
Could a workaround here be as simple as adding some redirect rules/pages in Vercel, @gabalafou?

**Comment by gabalafou** [comment]
Could be. I honestly don't know yet how URL routing works in the new site. This wasn't covered in the technical session with them. So we just need to ask. Add to Monday's agenda? and/or create GitHub issue around it? I feel like the issue is already covered by existing GitHub issues.

**Comment by bskinn** [comment]
Yes, if adding redirect routes to Vercel is easy, then those redirects are a good solution to multiple issues.

**Comment by bskinn** [comment]
Yes, if adding redirect routes to Vercel is easy, then those redirects are a good solution to multiple issues.

**Comment by marcin-antczak-naturaily** [comment]
@gabalafou @bskinn routing is based on folder names in Storyblok. From what I can see blog posts are stored in /library/blog folder. You can create /post folder directly into Storyblok root and move posts there

**Comment by bskinn** [comment]
Simple enough! I hadn't made that connection between the folders and the route structure. Also, I wasn't sure if that `/library/blog` folder structure might have been important for the Library page to pick up the blog posts correctly.

**Comment by bskinn** [comment]
Ok, for Quansight team reference, it looks like the tasks here are:

 - Move each blog post to `/post`
 - Revise the slug of each post to match the slug from the old site

@marcin-antczak-naturaily, if there's more we need to do for each post, please let us know.

**Comment by bskinn** [comment]
@marcin-antczak-naturaily I moved a trial blog post over to `/post`, and I'm consistently getting a 404 in the Storyblok preview, regardless of which preview URL I use.

Also, the post I moved to `/post` is no longer showing up in the carousel on the Storyblok preview of `/library`.

Is a Vercel re-deploy needed after a change like this?
