### ISSUE TITLE
[FEAT] Remove library type link if there are no library items of that type

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#185]
The [library page](https://quansight-consulting.vercel.app/library) has a bar of links that filter the library items by type (tutorials, videos, webinars, blog), as shown in the following screenshot:

<img width="979" alt="" src="https://user-images.githubusercontent.com/317883/173085676-cad0c5d3-6c98-438c-a8a0-dfb860abf38b.png">

If there are no items of, say, type webinar, then the webinar link should not show.

**Comment by gabalafou** [comment]
For launch, we may decide to simply remove this type filter bar until we have more content.

**Comment by bskinn** [comment]
If it would be easier to work within the current framework and not make direct frontend changes, perhaps it would suffice to remove everything but `blog` from the `Post Type` data source in Storyblok?

![image](https://user-images.githubusercontent.com/11325439/174668944-97f089cc-7a02-4831-8a8e-75ca6056ab2c.png)

There must be a way to add/remove these, but I don't have sufficient permissions in Storyblok to add or remove.


(OTOH, removing them may be a breaking change in some fashion that's not obvious from my position ~outside the codebase.)
