### ISSUE TITLE
[BUG] - New image assets added to Storyblok are distorted when rendered to the page

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#190]
### What site is this for?

Quansight LLC

### Expected behavior

When a new image asset is added to the site, the image should appear at its natural aspect ratio.

E.g., these images:

For the `/labs` page:
![man-with-smartphone](https://user-images.githubusercontent.com/11325439/173381818-ad63aacb-1a6e-4c24-a07b-6b3354b8dfaa.png)

For various consulting-related pages:
![Data-Engineering-_-MLOps](https://user-images.githubusercontent.com/11325439/173382479-8dba6782-74cd-43b9-a074-3dda49bd6538.png)

### Actual behavior

Images are not rendered at their natural aspect ratio, but instead are either squashed vertically (`/labs` page, in a Feature Article component):

![image](https://user-images.githubusercontent.com/11325439/173382260-d48c0dab-0344-456e-8ae7-2c2edc8f013f.png)

Or horizontally (`/consulting` page, in a Board List component):

![image](https://user-images.githubusercontent.com/11325439/173382616-f7ad0a03-9641-4dbd-b248-e86e086f9fb4.png)

### How to Reproduce the problem?

Visible in current (a/o 13 Jun 2022) Storyblok previews.

**Comment by gabalafou** [comment]
To me, this feels like something missing from [the Storyblok manual](https://docs.google.com/document/d/1HVaWKhepSxIQP1ZY9o7O_n3qCQpE8KdgD9KIaS4P-n4/edit#heading=h.enx0tixw76df).
