### ISSUE TITLE
[DESIGN] - Change design of Consulting drop-down in the header

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#194]
### What site is this for?

Quansight LLC

### Actual behavior

(1) 

The white background color and the black text color of the drop-down needs to be changed.

Desire:

* The green of the standard colors from the website theme for the background
* White for non-hovered text
* Black for hovered-over text

![image](https://user-images.githubusercontent.com/11325439/173932033-4df4745b-9a93-49d5-ab49-489aafadbbc9.png)

-----

(2)

The sub-items in the Consulting drop-down in the site header are center-justified within the drop-down, harming readability:

![image](https://user-images.githubusercontent.com/11325439/173410213-fbb8f7e0-2075-4ac1-ba54-6025eb1235ba.png)

Desire a left-align of the drop-down text, with a hanging indent on each service area name.

Adding a bold typeface to the "Consulting" item at the top of the header might also be good, to indicate that it is a top-level item, and the rest are sub-items.

**Comment by bskinn** [comment]
An alternative solution might be to retain the center alignment, but to reduce the line spacing within each services area, to make the visual clustering of the lines more obvious.

**Comment by gabalafou** [comment]
This issue has several sub-issues.

These sub-issues belong to Naturaily:

- Consulting menu items centered. This is non-standard. They should be left-aligned.
- Dropdown menu colors do not match design.

This sub-issue belongs to us:

- Special styling to sub-menu home page link. We could make it bold face. Another idea: the [accessible pattern that Deque uses](https://deque.com/) is to append the word "Overview" to the top item in each nav bar dropdown.

**Comment by bskinn** [comment]
@katebrack @irinafumarel -- Thoughts on Gabriel's third sub-issue?

**Comment by Katebrack** [comment]
Let's add the word "overview" to make it clear that's a separate page. On the current site, it's not clear that clicking "consulting" will take you to a separate page aside from what's in the dropdown menu. https://www.quansight.com/consulting @bskinn

**Comment by trallard** [comment]
Just saw this - we decided to make the drop-down white since the combination green with white text is not accessible (does not meet the WCAG minimum contrast requirements)

**Comment by bskinn** [comment]
FYI @irinafumarel.

Thanks for the heads up, @trallard!

As an alternative, would green with purple or black text meet the contrast spec?

**Comment by bskinn** [comment]
Presuming this change moves forward, my preference is for black text on the green background.

**Comment by Katebrack** [comment]
I agree. The white looks incomplete so if there's a way to add background color and still make it accessible that's ideal
