### ISSUE TITLE
[FEAT] -  Change all Text fields in all components, site wide, to Rich Text fields

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#195]
### What site is this for?

Quansight LLC

### Actual behavior

We wish to be able to apply formatting to numerous instances of text across the site. Many of these components currently offer only plaintext Text elements. We desire these to be Rich Text elements instead.

**Comment by gabalafou** [comment]
This seems like a duplicate or sub-issue of #212.

**Comment by bskinn** [comment]
It is related to #212, but #212 points to a much broader discussion on what components we have to work with in Storyblok overall, and will be a long term discussion.

This issue is a (hopefully) focused change allowing us soma high priority mods to the site design.

**Comment by bskinn** [comment]
This was meant to be `owner: Quansight` -- I have de-assigned Naturaily staff

**Comment by kherma** [comment]
@bskinn @gabalafou Hi, quick question... by 'text fields' you mean all textareas (which are mostly labeled as description) or all text inputs in components, including simple text field (which is mostly used for e.g. title, button texts, link text, any other short string etc...)?

Also, every page has title and description for seo purpose. I assume that the description could stay as textarea?

**Comment by bskinn** [comment]
First: please **halt work** on this until after launch. There are some new glitches emerging with the site rendering that are more important. New issue(s) to come shortly.

----

@kherma Ah, indeed, we were vague there, and didn't accurately describe what we wanted.

What we actually need to be converted is a relatively small set of the text fields:

- Teaser > Text
- Board List Item > Text
- Sticky Notes Item > Description (currently allows bold formatting, but that's it)
- Text Article > Text

> Also, every page has title and description for seo purpose. I assume that the description could stay as textarea?

Yes, the SEO fields can stay as textarea.

**Comment by kherma** [comment]
Oh... that is better... because after my initial investigation there were about 19 components to switch from textarea to Rich Text ^^ on LLC + Labs.
