### ISSUE TITLE
[FEAT] - Need Column subcomponents of Columns components to allow an empty Text field

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#196]
### What site is this for?

Quansight LLC

### Actual behavior

We are needing to use a Columns component for some items that have an icon Image and a Title, but no Text. Currently, Storyblok will not permit publishing a page with an empty Text field in a Column.

![image](https://user-images.githubusercontent.com/11325439/173414363-858b4c17-2307-4fdf-8e27-1d47cb3d7f45.png)

**Comment by tokordys** [comment]
We need to check Gabriel's PR and verify if it addresses the issue
