### ISSUE TITLE
[FEAT] - Quansight logo in site header should be a link to the homepage

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#205]
### What site is this for?

Quansight LLC & Labs

### Actual behavior

It's common for the logo in the header of a website to be a link back to the homepage of the site. This should be added.

**Comment by gabalafou** [comment]
I am a little uncertain when issues should be closed. When the pr is merged or when the fix can be verified on production? 

But sure, I'll close it for now, since #245 is working on the Vercel preview deploys, and it's difficult to imagine that it would stop working on the deploy to production.
