### ISSUE TITLE
[FEAT] - Add option to toggle display of date line for blog posts on an individual post basis

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#206]
### What site is this for?

Quansight LLC

### Actual behavior

The idea was raised in discussions: For some of the older blog posts, it might be useful to have a toggle controlling the display or not of the date line for individual posts, to avoid the impression that they are out of date.

**Comment by bskinn** [comment]
This post is an example: https://www.quansight.com/post/panel-holoviews-learning-aid

It was published in late 2020.

Really, this issue does not need to be separate from #223, though, so I'm going to close.

**Comment by trallard** [comment]
Adding more context since we discussed this on the marketing call - blogposts **must** keep their original date. They are not evergreen content but a "snapshot" of tools/methods/approaches/etc. at the time of publication. 

So this issue is not relevant and would not need implementation
