### ISSUE TITLE
[BUG] - Blog post preview images are cropped/resized undesirably when shown in Library preview

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#208]
### What site is this for?

Quansight LLC

### Actual behavior

For example:

![image](https://user-images.githubusercontent.com/11325439/173439448-547b1431-5f47-4805-9fe8-cb36cbefdc27.png)

The solution here *may* be to provide preview images with the correct aspect ratio to Storyblok somehow. If so, these instructions are needed.

If it's more complex than that, then more robust machinery/controls may be required.

**Comment by gabalafou** [comment]
I would be surprised if this isn't fixable with a little massaging of the HTML and CSS. The [link-images on the old site](https://www.quansight.com/blog) are all similar sized, in a grid, etc.

**Comment by marcin-antczak-naturaily** [comment]
Images should be:

Rendered size: | 264 × 164 px
Rendered aspect ratio: | 66∶41

I can remove `object-fit: cover;` property from CSS, unfortunately it will affect height of images and it's not good solution.

**Comment by bskinn** [comment]
cc @katebrack @bsodenkamp FYI.

This is for the preview images uploaded for each blog post.
