### ISSUE TITLE
[BUG] - Labs blog production preview not working

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#215]
### What site is this for?

Quansight Labs

### Actual behavior

In Storyblok, if you go to the Labs / Content / blog, and select the "prod" preview from the dropdown, you get a 500 error. Same if you open the preview url in a new window.

### Anything else?

I checked the other pages under Labs. Blog is the only that produces an error in the prod preview.

However, note that the following cases do not give a 500 when visiting the blog page:

- Local preview (from the Storyblok preview panel dropdown). For reference, I ran the local server from the latest commit on `develop` branch, which at the time of this writing was commit 9d8a3a4.
- Production but *not* preview (be sure to [Exit Prod Preview](https://quansight-website.vercel.app/api/exit-preview?) first!): https://quansight-website.vercel.app/blog
- I don't know if this URL is staging but the blog page also renders at this URL: https://quansight-labs-git-develop-quansight.vercel.app/blog

This may be an unrelated question, but I noticed that another URL, whose pattern suggests that it could be a staging URL, does not have a working build of the website: https://quansight-website-git-develop-quansight.vercel.app.

Is this why I've been seeing the build for Labs fail on a number of my PRs? #166 for example. Consulting build is okay, Labs is not.

**Comment by trallard** [comment]
I did have a 💡  moment - @gabalafou  when we set the `technical` and `non-technical` workflows for blogs - we did have the discussion that having Storyblok AND git-based additions to the blog would be problematic. So it makes sense that this is not working (to some extent - as we are not expected to make changes to the blog through Storyblok) 

I spoke to @noatamir and the alternative is to submit a PR and use the PR vercel preview to ensure all is good 👍🏽

**Comment by trallard** [comment]
That is something I am not sure about 🤷‍♀️ 
Could this have been disabled somewhere/somehow to intentionally turn it off to prevent issues?

**Comment by trallard** [comment]
I have  unassigned Naturaily folks as this is somewhat expected and we can perhaps explore this a bit more after launch
