### ISSUE TITLE
[FEAT] - Option to have team names below or above headshots

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#217]
### What site is this for?

Quansight LLC

### Expected behavior

Desire to be able to have team member names display below the headshots, not only above.

![image](https://user-images.githubusercontent.com/11325439/173928996-300ec264-a932-42f6-837b-bb5cbe8f81fc.png)

### Actual behavior

Names can only be positioned above the headshots.

**Comment by gabalafou** [comment]
Why? More context please.
