### ISSUE TITLE
[FEAT] - Add more options for configuring the layout of project logos in a Logos component

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#219]
### What site is this for?

Quansight LLC

### Actual behavior

Currently, the layout of the logos in a Logos component is hardwired: on desktop, logos are in two columns, with the final logo centered if there are an odd number.

For desktop (at least), desire to be able to lay these out in wider rows, with more configurability. We need to discuss the exact feature desired here with Design, including if control over different logo layouts on mobile vs desktop is desired.

**Comment by gabalafou** [comment]
Could you add a screenshot please?

**Comment by bskinn** [comment]
Of current behavior, or desired, or both?

**Comment by gabalafou** [comment]
I want to see what looks bad.
