### ISSUE TITLE
[FEAT] - Add options for controlling individual logo rendering size in a Logos component

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#220]
### What site is this for?

Quansight LLC

### Actual behavior

Currently, there are no controls for logo size, for the individual images included in a Logos component. This leads to icons rendering with different apparent sizes. It is desirable to be able to tune the render size of each logo, in order to achieve visual balance.

**Comment by gabalafou** [comment]
Could you add a screenshot please?
