### ISSUE TITLE
[FEAT] - Change implementation of 'Consulting' drop-down in header

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#221]
### What site is this for?

Quansight LLC

### Expected behavior

The "Consulting :arrow_down_small:" in the header should be split into two pieces.

The word "Consulting" should be a simple inline link to the main `/consulting` page.

The ':arrow_down_small:' would then toggle the drop-down menu for the consulting service areas. This drop-down menu would _only_ include the service areas, and _not_ a link to the main `/consulting` page itself.

![image](https://user-images.githubusercontent.com/11325439/173933114-3e58615a-e16b-4bde-a717-46669c5a9b63.png)

### Actual behavior

The entirety of "Consulting :arrow_down_small:" is a toggle for the dropdown menu.

**Comment by gabalafou** [comment]
I'm labeling this issue as "won't fix" because this conversation has already been had. The design you propose is not great for accessibility. Happy to discuss this further.

**Comment by gabalafou** [comment]
When I say this conversation has already been had, I mean that Irina and I talked about it from both a design and an accessibility perspective, and we decided to pattern our nav bar after [Deque's nav bar](https://deque.com/).
