### ISSUE TITLE
[FEAT] - Re-order the top portions of the Blog Article component and add a "deck" element

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#223]
### What site is this for?

Quansight LLC

### Expected behavior

We desire the elements of the top portion of the Blog Article component to be rendered in a different order, and for a "deck" element to be added (see [Newspaper Terms to Know](https://sites.bsu.edu/journalismworkshops/2016/06/07/newspaper-terms-to-know/) for definition).

Sequence:

- Title
- Deck (optional, with rich text formatting and font size options)
- Author byline (optionally with multiple authors, per #182)
- Dateline (optional, per #206)

### Actual behavior

The sequence of Blog Article top elements is currently:

- Title
- Dateline
- Single author byline

No functionality to include a 'deck' is currently available.

**Comment by bskinn** [comment]
This was meant to be `owner: Quansight`, @tokordys, please disregard.

**Comment by trallard** [comment]
From the original issue on the `date` toggling or so https://github.com/Quansight/Quansight-website/issues/206#issuecomment-1175054704
