### ISSUE TITLE
[FEAT] - Option to change vertical extent of Teaser component

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#224]
### What site is this for?

Quansight LLC

### Actual behavior

We like the visual styling offered by the Teaser component, but sometimes it takes up too much vertical space for what we want to do with it.

We desire the option to reduce the vertical extent (height padding/margin?) of the Teaser component.

**Comment by gabalafou** [comment]
Rather than create variants of a component, I would want to see if there's a way to create a single variant that works well (or well enough) for desired use cases.

**Comment by bskinn** [comment]
This is `owner: Quansight`, @tokordys, please disregard
