### ISSUE TITLE
[BUG] - Headers are not auto-anchored by our markdown renderer which makes intra-document links break

### ISSUE THREAD

**Issue by noatamir** [Quansight/Quansight-website#233]
### What site is this for?

Quansight Labs

### Expected behavior

within a markdown blog:

```
 ### headline

Lorem ipsum colom [headline](#headline)
```
should function as an intra-document link

### Actual behavior

The headline in the example is rendered as an h3 without an anchor, so later on in the blog post, there's a link back to that h3, but it doesn't work.

**Comment by marcin-antczak-naturaily** [comment]
@noatamir @trallard Could you provide URL to example blog post?

**Comment by noatamir** [comment]
@marcin-antczak-naturaily this was discovered by @gabalafou when we made the [first blog post](https://quansight-labs.vercel.app/blog/thoughts-on-reviewing-for-accessibility#My-review-checklist) in #198 

In this blog the H3 "My review checklist", and the H4s "Text", and "Not Text" are used as intra-document links, get rendered as links, but break.
