### ISSUE TITLE
[DOC] - Document folders and files

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#235]
Quansight is a company with a lot of code repositories, each with their own tools and conventions. Our team works across repos and technology stacks, so it's important that we not only follow conventions but that we try to make everything as self-explanatory as possible. 

To that end, I would like most folders in this repo to have documentation explaining:

- What purpose the folder serves (what belongs in this folder, what does not belong in this folder)
- A quick explanation of each file in the folder

These are the folders that I think should have such descriptions:

```
/
/.github/
/.husky/
/.vscode/
/apps/
/apps/consulting/
/apps/labs/
/libs/
/tools/
```

**Comment by trallard** [comment]
Disagree here - readmes in each directory can be confusing.

I'd recommend a single infrastructure.md or configuration.md containing the relevant information

**Comment by trallard** [comment]
Also it is necessary to describe each single file in the repo?

**Comment by trallard** [comment]
Rationale for a single architecture file: https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html
