### ISSUE TITLE
[DOC] - How to configure Zapier integrations for contact info submission forms?

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#240]
### What site is this for?

Quansight LLC

### Actual behavior

The LLC site has a Contact Form on the `/about` page. We actually now also want to include similar forms at the bottom of all of the individual services pages.

![image](https://user-images.githubusercontent.com/11325439/174678687-3b086757-5683-490a-8ef7-f8502890b238.png)

All of these forms need to submit their data to different Pipedrive pipelines, as a function of the page where the contact form was submitted from. Our understanding is that these submissions are mediated by Zapier integrations, which feed the contact form info over to the correct Pipedrive pipeline.

We need to be able to define all of the necessary Zapier integrations and connect them to the proper Pipedrive pipelines. We currently have neither access to nor instructions for the Zapier integrations.

**Comment by tokordys** [comment]
@bskinn Current Zapier instruction is in the manual: 

https://docs.google.com/document/d/1HVaWKhepSxIQP1ZY9o7O_n3qCQpE8KdgD9KIaS4P-n4/edit#heading=h.ozb4egkd5ifs

**Comment by bskinn** [comment]
We have this sorted.
