### ISSUE TITLE
[FUTURE/FEAT] - Re-implement contact forms to eliminate paid Zapier integration layer

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#242]
### What site is this for?

Quansight LLC

### Actual behavior

Per @bsodenkamp, it should be possible to implement the contact forms on About Us and on the individual service pages to pass submitted data directly to Pipedrive, without the Zapier integration layer in between. This implementation would not require additional costs beyond what we're already paying for Pipedrive; whereas we will need enough configured Zaps, and likely enough Zaps per month in peak seasons, to require a paid tier of Zapier for the integrations as currently required.

There may be some advantages to retaining the Zapier middle layer -- for example, if we might want to fork the contact information and send it to some destination in addition to Pipedrive. Discussion needed.

**Comment by bskinn** [comment]
Good to know that context, I hadn't known.

These considerations stand in tension with the costs of the Zapier integration layer, then.

**Comment by bsodenkamp** [comment]
The widget is configurable as far as appearance goes, when we integrated these forms into the OpenTeams site the folks at Elastec found a way to do it somehow. As for accessibility, I do not know what options we have there. I would need to know more about the specific requirements for a form, and then maybe we could ask Elastec if it is possible.

**Comment by trallard** [comment]
Yup, we did not anticipate that we would need that many forms - and hooks? Originally the design only had one (maybe two?) forms

> The widget is configurable as far as appearance goes
within certain constraints - yes 

Re accessibility:
- Forms element only: http://web-accessibility.carnegiemuseums.org/code/forms/ https://www.w3.org/WAI/tutorials/forms/instructions/ plus any other related WCAG requirements depending on how the forms are put together

**Comment by bsodenkamp** [comment]
The number of forms from PipeDrive we have on the current site is 9, and there are two additional forms that still utilize Wix forms that forward to an email inbox (if we can forward to an email inbox for these still that would be good but they could be switched to PD).

I will see if anyone at Elastec can look into what they did with the other form to find out if these accessibility requirements can be accommodated given the PD code.

**Comment by bskinn** [comment]
After implementation of #617, we now can handle all `Form` component submissions via a single Zap, and this Zap is configured to forward the form info also to cognizant parties.

The cost structure of Zapier has been approved.

So, I believe there are no outstanding motivations to migrate away from Zapier. Thus, I'm closing this issue.
