### ISSUE TITLE
[DISCUSS] - Should we be using pre-release dependencies in package.json?

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#251]
I just noticed that some of the version strings in package.json use pre-release versions, like this:

```
    "next": "^12.1.5-canary.6",
    "react-responsive": "^9.0.0-beta.8",
```

This seems like not a great idea to me. I'm wondering if there was a plan to update these version strings.

**Comment by marcin-antczak-naturaily** [comment]
You are right. We should not. Especially when version 12.1.6 is released already as stable.

**Comment by marcin-antczak-naturaily** [comment]
Prepared a PR with some updates + nextJS set to 12.1.6
