### ISSUE TITLE
Missing: favicon

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#299]
Just putting this here so we don't forget to add favicons to Labs and Consulting

**Comment by ericdatakelly** [comment]
Please consider dark themes too.  Here's the Quansight favicon in a dark theme Chrome browser.  It's hard to see and not very attractive.

![image](https://user-images.githubusercontent.com/24855669/180068002-c1b5adfd-039b-4c7c-8175-55aa063b4d1e.png)
