### ISSUE TITLE
[BUG] - External URLs in 'Footer Navigation > Footer Link' components are treated as internal navigation, leading to broken links

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#301]
### What site is this for?

Quansight LLC

### Expected behavior

When an external URL is applied to a Footer Link component with a surrounding Footer Navigation, that URL should be used as-is.

![image](https://user-images.githubusercontent.com/11325439/177198392-b4822c51-85aa-4416-9ba8-95d14e8f31ea.png)

### Actual behavior

Instead, the URL is treated as if it were an internal slug:

![image](https://user-images.githubusercontent.com/11325439/177198657-2299c010-2474-435f-8152-e9fe38d545e7.png)

### Anything else?

The Footer is a shared component, so this likely affects any external URLs in the Labs site footer, also.

**Comment by kherma** [comment]
@bskinn @gabalafou  [OPINION]: One thing that comes to my mind is to create more universal solution. What I mean is to create a separate Link Component that can replace standard storyblok link field.

### Current behaviour

For now, there are about 15 components that uses link field. Although storyblok link field always gives you an option to choose internal or external links, the accual behaviour of link is all handeled in code e.g. We use next/link component in places that (based on multiple discuccions on figma) are leading to internal pages and reqular a tag for external resources. 

### Optional change

The idea is to Create Link component that will replace all links fields ( similar to replacing text areas with Rich Text fields from #123). Then every link on website can be eather internal or external... Obviously Link component will have additional fields as query params, if link target should open in new tab, etc... 

A similar solution is already implemented in LLC library where, even if each tile is same component, they can eather lead to internal or external resource.

### Others

I can always implement it in Footer for now and then if you will be interested add Link to other components... or if you don't feel the need for solution like that I can simply change the FooterLink component to allows external links and query params.

### Pros: 
- most flexible solution 
- reduced error probability 
- Links logic encapsulated in one place

### Cons:
- time to implement in every component ( but creating the structure and adding it to the footer as a starting point shouldn't take long ) 
- every link can be internal  / external which means that navigation links too... so there can be situation where someone accidently add external link to navbar ( but while adding navbar link you usually want to choose a page target from dropdown and currently you also has option for external links in navigation soo Imho it's not such a big thing )

**Comment by gabalafou** [comment]
@kherma i thought you fixed this issue in https://github.com/Quansight/Quansight-website/pull/245/files

**Comment by bskinn** [comment]
oh -- I skimmed your Cons too fast, @kherma 

> ( but creating the structure and adding it to the footer as a starting point shouldn't take long )

If it wouldn't take much longer to implement the fix for these footer navigation links using this proposed mechanism, then sure, please go ahead and fix it the way you've proposed.

**Comment by bskinn** [comment]
@kherma First step, figure out and fix the breakage in the footer line spacing, per my comment on #310.

Then, please go ahead and create a new issue for this re-working of the links, but hold off any work on it until after launch. At minimum, for the LLC site #181 and then #195 are higher priority.

**Comment by kherma** [comment]
@bskinn padding sould be fixed now, please double check

**Comment by bskinn** [comment]
@kherma Yep, once you fixed the build breakage, the spacing is back to what it should be -- thanks!

**Comment by gabalafou** [comment]
Can #301 be a fix for this?

**Comment by bskinn** [comment]
You mean #311, @gabalafou?

**Comment by gabalafou** [comment]
Yeah, we can scratch my PR. I did not intend to duplicate or supersede @kherma's PR (#310). What happened was that I got very confused because #301 (issue) and #310 (PR) both have the same title (and almost the same number), so I thought there was only an issue, not a solution.
