### ISSUE TITLE
[BUG] - Labs header does not align with Labs footer

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#312]
### What site is this for?

Quansight Labs

### Expected behavior

The header content (text) should be contained within the same width as the footer text. 

Also, like the footer, the header's background should be allowed to fill the entire width of the page. 

So basically, the header just needs to have padding that matches the footer's. When I say padding, I do not specifically mean that this needs to be fixed with css padding. I just mean it needs to visually match the footer.

### Actual behavior

The header content is allowed to expand to nearly the full width of the browser window.

![screenshot of Labs home page with annotations showing how to align the header and footer](https://user-images.githubusercontent.com/317883/177346235-0f3abcbe-ee23-47f4-90eb-c07219e0c80d.png)

### How to Reproduce the problem?

1. Visit the following build of the Labs homepage: https://quansight-labs-live-4ep78v7qk-quansight.vercel.app/
2. Make sure your browser window is wide.
3. Scroll up, scroll down. Notice the header. Notice the footer.
4. Observe that the header and footer are not aligned.

**Comment by kherma** [comment]
@gabalafou Can I start working on this one now?

**Comment by bskinn** [comment]
Curious - shouldn't this issue have auto-closed when you merged #313, @kherma?
