### ISSUE TITLE
Improve phone validation in contact form

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#336]
When @bskinn [reviewed the contact form](https://github.com/Quansight/Quansight-website/issues/152#issuecomment-1176766228), he wrote:

> NO PHONE VALIDATION: Accepts even non-numeric inputs

It seems like that could be improved to only accept the set of characters described by something like the following regular expression character class: [+0-9.()\s-].

**Comment by bskinn** [comment]
Would we really want to allow the whole `\s` character class? I'd be inclined to tighten to [+0-9.() -]. (Or are there some exotic unicode space-equivalents that we'd want to permit?)

**Comment by trallard** [comment]
Note that we might want to also allow for `+` since this is often required for international number capture

**Comment by bskinn** [comment]
Yes, I accounted for `+` in my proposed regex character class.
