### ISSUE TITLE
[ASSETS] - IPython logo needs to be added to the Jupyter Technologies services page

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#341]
### What site is this for?

Quansight LLC

### Actual behavior

Per Eric Kelly, the Jupyter Technologies services page should include the IPython logo.

**Comment by bskinn** [comment]
@irinafumarel, I believe you're best equipped to take care of this?

Please note [this new (draft) workflow for Storyblok-only content/assets changes](https://github.com/Quansight/Quansight-website/wiki/LLC:-Storyblok-Change-Workflow-for-Content-and-Assets). This PR will be a great task for a first test of it, I think.

**Comment by ericdatakelly** [comment]
Specifically, I'm referring to the logos under this text, in case it's not clear: "Some of the Open Source Projects We Use for Jupyter & JupyterHub"

**Comment by bskinn** [comment]
Yep, @ericdatakelly, that's where we'll be putting it. Thanks for making sure!
