### ISSUE TITLE
[BUG] - RSS feed is broken, "hello world" posts showing up on Planet Python/SciPy

### ISSUE THREAD

**Issue by rgommers** [Quansight/Quansight-website#346]
### What site is this for?

Quansight Labs

### Expected behavior

The RSS feed at https://labs.quansight.org/rss.xml should contain valid content for new blog posts.

### Actual behavior

The current RSS feed is broken, showing dummy posts with today's or yesterday's date. Those are showing up on https://www.planetpython.org/ and https://planet.scipy.org/:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/98330/178655064-ac575100-140f-4d25-9081-5f484a469f35.png">

<img width="537" alt="image" src="https://user-images.githubusercontent.com/98330/178655104-9c033dea-de50-47e2-b711-160f4cc816ed.png">

I was made aware of this through https://github.com/python/planet/issues/517. We should fix this asap, or remove the feeds from the Planet aggregators.

### How to Reproduce the problem?

Looking at https://labs.quansight.org/rss.xml is enough. After the fix, please check with an RSS feed reader that the content is correct.

**Comment by bskinn** [comment]
This should now be fixed, @rgommers. Sorry it took us so long! I'd looked a while ago at the blog posts directory and seen that the 'hello world' posts were gone, and figured it was all sorted. Did not realize that the RSS generation was broken and had been disabled.
