### ISSUE TITLE
[BUG] - Labs and Consulting blog RSS feed generation is broken, and disabled

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#403]
### What site is this for?

Quansight Labs
Quansight Consulting

### Expected behavior

RSS feed generation for the blog posts for both sites should occur on every build.

### Actual behavior

Using the Labs site as an example:

The RSS feed is not generated, as the function call to generate it is [commented out](https://github.com/Quansight/Quansight-website/blob/25b970931afdf4d1498ad376d91e355fe4e7e0a3/apps/labs/pages/blog/index.tsx#L211).

Upon testing, uncommenting the generation function [causes the Labs site build to break](https://vercel.com/quansight/quansight-labs-live/71aooYpEezRdfL2ppTVcBkk1V66p).

This needs to be fixed. ~We will have to decide whether we also want an RSS feed generated for the LLC blog, as part of #396.~ Yes, we desire this for Consulting blog also.

**Comment by bskinn** [comment]
Added the LLC label since this will apply to LLC blog after #396 is complete.

**Comment by bskinn** [comment]
#739 is addressing the broken RSS feed for Labs.

Further discussion on the approach to expanding implementation of the RSS feed for Consulting blog, prior to actually starting work, should take place here.

**Comment by bskinn** [comment]
I've created #741 to track any discussion on RSS for the Consulting blog, and am closing this one after the merge of #739.

**Comment by kalvdans** [comment]
Sorry for posting a question here, but what is the URL to the rss feed of the Labs blog? There's no autodiscover tag on https://labs.quansight.org/blog .

**Comment by bskinn** [comment]
No problem at all, @kalvdans! That autodiscover tag sounds like something we should add, as well as a direct RSS link in the footer, probably.

The feed is at https://labs.quansight.org/rss.xml.

Thanks for your interest!
