### ISSUE TITLE
[FEAT] - Implement Google Ads on LLC site

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#404]
### What site is this for?

Quansight LLC

### Actual behavior

The site needs to be configured to interop with our Google Ads campaigns. We have the needed HTML and AMP tag/script content to be inserted into the pages.

At this time, we wish a conversion event to be submitted to Google Ads when a visitor successfully submits their contact information into one of the `Form` Storyblok components on `/about-us`, on any one of the seven services pages, or on the `/qhub` page.

The `Form` component is implemented as a shared component, but it is currently only used on the LLC site, and so the conversion-event trigger can just go into that component. 

Likely, the setup scripts/tags to be injected into `<head>` should just go in the global template for the LLC site.

These details are open to discussion, if a better implementation is possible. Also, given the possibility that we will want to define additional conversion events in the future, the code modifications should be done in a way that streamlines addition of the code needed for these additional events.

**Comment by bskinn** [comment]
From Brandon, as told to him by our Google Ads rep, as something (additional?) to accomplish as part of this issue:

> We will have to update our conversion tracking code on the website to setup enhanced conversions, to prevent engagement drops from 3rd party cookies going away. Please follow the 3 steps below.
> - Create a conversion tracking through Global Site Tag. Instructions [here](https://support.google.com/google-ads/answer/12216424?hl=en).
> - Accept customer data terms. Go to Tools & Settings --> Conversions --> Settings --> Customer Data Terms --> Accept & Save
> - Implement enhanced conversions through Global Site Tag. Go to the Conversions page on Google Ads and click into your new conversion action, scroll down to enhanced conversions, turn on, and follow implementation instructions. You can also view them [here](https://support.google.com/google-ads/answer/9888145?hl=en).

**Comment by bskinn** [comment]
Our SEO/etc. consultants will be assisting with a redesign of our ads campaigns. Their technical requirements will need to be incorporated into the technical solution implemented here. More details to come once available.

**Comment by tokordys** [comment]
hi @bskinn Did your consultants manage to define the technical requirements so we have a full picture of this ticket?
