### ISSUE TITLE
[FEAT] - Add redirect from LLC `/labs` slug to `labs.quansight.org`

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#408]
### What site is this for?

Quansight LLC

### Actual behavior

Right now, [`/labs` on LLC site](https://quansight.com/labs) just 404s. A redirect to the Labs site seems like a simple, prudent change.

Thoughts, @trallard / @rgommers / @dharhas?

**Comment by rgommers** [comment]
makes sense to me
