### ISSUE TITLE
[BUG] - Sponsor logos on Labs site front page went missing

### ISSUE THREAD

**Issue by rgommers** [Quansight/Quansight-website#441]
### What site is this for?

Quansight Labs

### Expected behavior

The AMD and Bodo.ai logos went missing from the front page. Can they please be re-added?

This is what was on the front page of the old site:

![sponsors](https://user-images.githubusercontent.com/98330/189398112-9a7eef84-fecf-44d6-b8db-0fbd109081fd.png)

### Actual behavior

And here is what is on the new site right now:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/98330/189398258-eb2a0065-02d7-4bad-bcce-ae64b2411f6e.png">

### Anything else?

This should have some priority - acknowledging funders of past work is important.

**Comment by bskinn** [comment]
@noatamir -- I think you're best positioned to tackle this, since you have a Storyblok seat and you're most familiar with the Labs site?

**Comment by bskinn** [comment]
@katebrack Is the DE Shaw logo also prohibited on the Labs site?

**Comment by rgommers** [comment]
> @Katebrack Is the DE Shaw logo also prohibited on the Labs site?

I have the email with written permission, will forward to both of you.

**Comment by noatamir** [comment]
Updated storyblock to include AMD and bodo.ai. The change will be live in the next merge to main.
<img width="988" alt="Screenshot 2022-09-14 at 22 16 10" src="https://user-images.githubusercontent.com/6564007/190253583-04568e3f-9d8b-48c5-b190-7deb06a06d3b.png">

**Comment by trallard** [comment]
This is now live so will close this issue

**Comment by rgommers** [comment]
Thanks @noatamir and @trallard!
