### ISSUE TITLE
[MAINT] - Formalize recommended reviewers in PR template, with note in README

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#446]
### What site is this for?

Quansight LLC, Quansight Labs

### Actual behavior

Per discussion in #435, we should indicate who the go-to reviewers are for the different types of PR the repo is likely to have.

At present, the plan is to put this information in the PR template, with an accompanying note in the README that indicates the PR template as the source of truth; plan is open for discussion.

Tasks:

- [ ] Identify the categories of PR
- [ ] Choose the go-to reviewer(s) for each category
- [ ] Revise the PR template
- [ ] Add note to README

**Comment by trallard** [comment]
That is what the CODEOWNERS (now deleted file) is meant to help with identifying reviewers. 

For content - folks usually request reviews from Ralf, Noa, or myself - plus any other peers who they have worked with or would have any insights

For the broader codebase I anticipate it will be a mixture of Gabriel and whoever ends up in the review cycle for the LLC blog

**Comment by bskinn** [comment]
&lt;checks the CODEOWNERS docs&gt;

Ah, looks like the CODEOWNERS was [under-configured](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) -- that's why it wasn't working in a useful way.

Based on your recommendations, @trallard, perhaps a new CODEOWNERS like the following would be good. If so, I can create a PR and we can refine there as needed?

```
# Gabriel as default owner
*   @gabalafou

# Noa as default reviewer for Labs blogs and assets
# Tania/Ralf/others to be manually added as appropriate
/apps/labs/posts   @noatamir
/apps/labs/public/posts   @noatamir

# Noa as default reviewer for changes to Labs Storyblok content
# Tania/Ralf/others to be manually added as appropriate
/apps/labs/CHANGELOG.md   @noatamir 

# Brian as default reviewer for changes to LLC Storyblok content
# Kate/others to be manually added as appropriate
/apps/consulting/CHANGELOG.md   @bskinn

```

**Comment by trallard** [comment]
Can we turn the above in a PR for review @bskinn ?

**Comment by bskinn** [comment]
Done, @trallard -- see #458
