### ISSUE TITLE
MAINT - update release calendar

### ISSUE THREAD

**Issue by trallard** [Quansight/Quansight-website#630]
@pavithraes will be taking @noatamir place as release manager / content reviewer so we need to make the following changes

- [x] update codeowners entry
- [x] release calendar in README.md
- [x] Notion page "Blogging at Quansight Labs"

**Comment by pavithraes** [comment]
@trallard I've updated the Notion page "Blogging at Quansight Labs" to take over as the person-to-contact, as well as the page maintainer.

And, thanks `@bskinn` for updating relevant parts in this repo!

Closing as done!
