### ISSUE TITLE
[CONTENT] Fixes for Labs 2022 Annual Report

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#673]
This issue is for collecting and status-reporting fixes on or related to the 2022 Labs Annual Report.

In order to leverage Github's checklist tracking feature on issues, please edit all items into this top description field.

For fixes involving the repo, we can link PRs into these items as they are created.

For fixed directly to the Labs document itself, we will have to decide at what point they're fixed for the purposes of this issue. Perhaps when they're fixed in the canonical Illustrator file?

cc @katebrack @trallard @irinafumarel @gabalafou 

---

- [x] @pavithraes The blog title is great but when you see it elsewhere, it needs more of a description. See the example below from the Linkedin post. "Celebrating Growth and Sustainability" in open source?
  - #672 
- [x] @MarsBarLee The banner image for LinkedIn isn't working. I think it's too thin...see screenshot. Can you widen the image but not the text? I'd double check the image sizes for that as they vary depending on the source.
- (From @melissawm) My name does not have a hyphen, but this is not critical. If there's a chance to remove, I'd appreciate :slightly_smiling_face:
  - [x] Instead of Melissa Weber-Mendonça it should be Melissa Weber Mendonça. This is optional but it is in several pages :slightly_smiling_face:
  - [x] On page 16, it is actually inverted: Melissa Mendonça-Weber should be Melissa Weber Mendonça
  - [x] On page 13, Melissa Weber-Mendonça’s long-standing contribution to the Scientific Python Community was recognized by two awards this year: the NumFOCUS’s project sustainability award and Python Brasil’s Python Dorneles Treméa and Jean Ferri award given to those dedicated to support the ~Bazil~ Brazil (maybe even Brazilian?) Python community
- [x] On page 21 the footnote is not rendered correctly:  
      &nbsp;
      <img src="https://user-images.githubusercontent.com/11325439/219408881-4dee892c-0527-4c9a-b015-b40a2d7d00ba.png" width="600px" />
- [x] On page 7, the period is outside the quotes for Pavithra's quotation but inside the quotes for the other two.
- [x] The new PDF needs to go into Labs SB assets, and the URL updated again in the site codebase, before we can build.

**Comment by melissawm** [comment]
Just a note, above I forgot to highlight 
Melissa Weber-Mendonça’s long-standing contribution to the Scientific Python Community was recognized by two awards this year: the NumFOCUS’s project sustainability award and Python Brasil’s ~~Python~~ Dorneles Treméa and Jean Ferri award given to those dedicated to support the Bazil Brazil (maybe even Brazilian?) Python community

**Comment by bskinn** [comment]
Revised PDF is uploaded to Labs SB, and the redirect is changed to point to this new PDF in #676.
