### ISSUE TITLE
[BUG] - Broken link on quansight.com/consulting

### ISSUE THREAD

**Issue by pavithraes** [Quansight/Quansight-website#716]
### What site is this for?

Quansight Consulting

### Expected behavior

On https://quansight.com/consulting, the "Learn more" button under "Infrastructure, Scaling & Acceleration" should point to: https://quansight.com/infrastructure-scaling-acceleration
 

### Actual behavior

Currently, it points to an outdated link: https://quansight.com/service-infrastructure-scaling-acceleration

### How to Reproduce the problem?

![Screenshot 2023-04-07 at 8 26 42 PM](https://user-images.githubusercontent.com/33131404/230630386-285edb16-f085-4fd0-8bdc-9898afaad649.png)

### Anything else?

We can also consider adding a redirect from the old link `https://quansight.com/service-infrastructure-scaling-acceleration` to the new slug https://quansight.com/infrastructure-scaling-acceleration

cc @bskinn

**Comment by bskinn** [comment]
☹️ This was fine at one time. It never pointed to the `service-...` slug before.

I wonder if Storyblok's database is corroding...this seems like a similar problem to what we was recently with the broken homepage hero image on mobile.

Should be a straightforward fix, I'll get to it ASAP today and we can rebuild.
