### ISSUE TITLE
[BUG] - Link to Nebari Services page in footer opens in new tab/window despite being set to open in same tab

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#726]
### What site is this for?

Quansight Consulting

### Expected behavior

The link to the Nebari Services page in the footer...

<img width="136" alt="image" src="https://user-images.githubusercontent.com/11325439/231934210-c2b7e11a-11a3-4b76-95b3-44d96a7105cf.png">

... is set in Storyblok to open in the same tab:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/11325439/231934294-e00389fd-b107-464d-88ba-4a12d493b04b.png">

It should open in the same tab when clicked.

### Actual behavior

It does not. It opens in a new tab. This is reflected in a `target="_blank"` attribute that is present in the `<a>` element:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/11325439/231934494-66279032-be52-4172-ad44-02d8a5a47dca.png">

`target="_blank"` is also present when the "Open in new window" setting is toggled on.

### Anything else?

Switching the "Open in new window" toggle on, saving, switching it back off, saving, and publishing does NOT fix the problem.

Notably, the footer link to the Labs site also (a) opens in a new tab, and (b) has "Open in new window" DISABLED:

<img width="241" alt="image" src="https://user-images.githubusercontent.com/11325439/231934683-1dc87aae-02a9-4468-b8d5-5bae81114bea.png">

This suggests that perhaps all `URL` style `Footer Link` components (and possibly *all* `Link` components?) insert `target="_blank"` regardless of the value of the "Open in new window" toggle.

**Comment by ishaan9006** [comment]
@bskinn Hey! Can I work on this issue?

**Comment by bskinn** [comment]
Hi, @ishaan9006 -- thanks for your interest!

Unfortunately, the repository and codebase are not set up right now to accept external contributions (no LICENSE, etc.). So, we would not be able to accept any PRs.
