### ISSUE TITLE
[BUG] - Domain-directed modeling post is missing images

### ISSUE THREAD

**Issue by ericdatakelly** [Quansight/Quansight-website#755]
### What site is this for?

Quansight Consulting

### Expected behavior

This post would show images: https://quansight.com/post/robust-predictions-and-increased-interpretability-through-domain-directed-modeling/
cc: @bskinn 

### Actual behavior

The post does not show its images.

### How to Reproduce the problem?

Click [here](https://quansight.com/post/robust-predictions-and-increased-interpretability-through-domain-directed-modeling/) and look for images.

**Comment by bskinn** [comment]
Yep, thanks for pointing this out, @ericdatakelly -- we actually migrated the Consulting site from the Jamstack to Wordpress a month or so ago, and not all the images and post/page formatting made it through the migration cleanly. 

Going back through and getting everything in order is on the to-do list.
