### ISSUE TITLE
[LABS BLOG] 2023-09 Array API post tweaks

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#775]
Some minor things I noticed when reviewing in the course of the #771 release PR.

Attn @thomasjpfan.

---

I would center this image:

<img width="874" alt="image" src="https://github.com/Quansight/Quansight-website/assets/11325439/5da8d85a-c120-4697-9d75-b45ba28fa14d">

---

Could we add a link to the proper issue tracker, to make it easier for readers to find?

<img width="833" alt="image" src="https://github.com/Quansight/Quansight-website/assets/11325439/76fa327e-f8f8-4b1f-9390-c735ea8e051b">

**Comment by thomasjpfan** [comment]
I opened https://github.com/Quansight/Quansight-website/pull/778 to address the concerns.
